name: GIF comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Add funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: GIFComment
        with:
          GIPHY_TOKEN: ${{ secrets.GIPHY_KEY }}
          comment_type: 'gif'
